# Generated by Django 3.2.6 on 2021-09-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_remove_users_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
