# Generated by Django 3.2.6 on 2021-09-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0009_alter_users_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
